// ============================================================
// We Smile Dental — Central CMS Data Store
// Single source of truth for branches, services, doctors,
// schedules, success stories, and editable section copy.
// An admin dashboard would mutate this object via API.
// ============================================================

// ---------- Branches ----------
const BRANCHES = [
  {
    id: 'ladkrabang',
    name: 'Ladkrabang',
    nameTh: 'ลาดกระบัง',
    label: 'Flagship',
    labelTh: 'สาขาหลัก',
    address: '222/15 ถนนหลวงแพ่ง แขวงทับยาว เขตลาดกระบัง กรุงเทพฯ 10520',
    addressEn: '222/15 Luang Phaeng Rd., Lat Krabang, Bangkok 10520',
    phone: '063-879-8448',
    hours: '09:00 — 20:00',
    hoursTh: 'เปิดทุกวัน · 09:00 — 20:00',
    landmarks: ['Near Lat Krabang ARL', '8 min to Suvarnabhumi'],
    landmarksTh: ['ใกล้สถานี ARL ลาดกระบัง', '8 นาทีจากสุวรรณภูมิ'],
    // pin coords on faux 600×400 svg
    pin: { x: 0.52, y: 0.48 },
    rooms: 8,
  },
  {
    id: 'suvarnabhumi',
    name: 'Suvarnabhumi',
    nameTh: 'สุวรรณภูมิ',
    label: 'Airport branch',
    labelTh: 'สาขาสนามบิน',
    address: '88/2 ถนนกิ่งแก้ว แขวงราชาเทวะ อ.บางพลี สมุทรปราการ 10540',
    addressEn: '88/2 King Kaeo Rd., Racha Thewa, Bang Phli, Samut Prakan 10540',
    phone: '063-879-8449',
    hours: '10:00 — 21:00',
    hoursTh: 'เปิดทุกวัน · 10:00 — 21:00',
    landmarks: ['5 min from Suvarnabhumi terminals', 'Free valet parking'],
    landmarksTh: ['5 นาทีจากสนามบินสุวรรณภูมิ', 'มีบริการรับรถวีไอพี'],
    pin: { x: 0.66, y: 0.42 },
    rooms: 6,
  },
  {
    id: 'romklao',
    name: 'Romklao',
    nameTh: 'ร่มเกล้า',
    label: 'Community branch',
    labelTh: 'สาขาชุมชน',
    address: '45 ถนนร่มเกล้า แขวงคลองสามประเวศ เขตลาดกระบัง กรุงเทพฯ 10520',
    addressEn: '45 Romklao Rd., Khlong Sam Prawet, Lat Krabang, Bangkok 10520',
    phone: '063-879-8450',
    hours: '09:00 — 19:00',
    hoursTh: 'เปิดทุกวัน · 09:00 — 19:00',
    landmarks: ['Inside Mega Lifestyle Plaza', 'BTS shuttle every 20 min'],
    landmarksTh: ['ในศูนย์ Mega Lifestyle Plaza', 'มีรถรับ-ส่ง BTS ทุก 20 นาที'],
    pin: { x: 0.36, y: 0.34 },
    rooms: 5,
  },
  {
    id: 'onnut',
    name: 'On Nut',
    nameTh: 'อ่อนนุช',
    label: 'City branch',
    labelTh: 'สาขาในเมือง',
    address: '1199 ถนนสุขุมวิท 77 แขวงพระโขนงเหนือ เขตวัฒนา กรุงเทพฯ 10110',
    addressEn: '1199 Sukhumvit 77, Phra Khanong Nuea, Watthana, Bangkok 10110',
    phone: '063-879-8451',
    hours: '11:00 — 21:00',
    hoursTh: 'เปิดทุกวัน · 11:00 — 21:00',
    landmarks: ['Connected to On Nut BTS exit 2', '24-hr secure parking'],
    landmarksTh: ['เชื่อม BTS อ่อนนุช ทางออก 2', 'ที่จอดรถปลอดภัย 24 ชม.'],
    pin: { x: 0.22, y: 0.62 },
    rooms: 4,
  },
];

// ---------- Services + Sub-services ----------
// Each top-level service is a "category". The drill-down page
// lists sub-services with their own copy, pricing, and before/after gallery.
const SERVICES = [
  {
    id: 'orthodontics',
    icon: 'move-horizontal',
    title: 'Orthodontics',
    titleTh: 'ทันตกรรมจัดฟัน',
    blurb: 'Braces and clear aligners planned by board-certified orthodontists.',
    blurbTh: 'จัดฟันและจัดฟันใส ออกแบบโดยทันตแพทย์เฉพาะทางที่ผ่านการรับรอง',
    long: 'Whether you want classic braces, low-friction self-ligating brackets, or near-invisible aligners — we plan every case in 3D and walk you through the timeline before treatment begins.',
    longTh: 'ไม่ว่าจะเลือกจัดฟันโลหะแบบดั้งเดิม ระบบดามอนแบบลดแรงเสียดทาน หรือจัดฟันใสที่แทบมองไม่เห็น เราวางแผนทุกเคสด้วยระบบ 3D และอธิบายขั้นตอนทั้งหมดก่อนเริ่มรักษา',
    priceFrom: 35000,
    priceLabel: 'From ฿ 35,000',
    duration: '12 — 30 months',
    feature: true,
    subServices: [
      {
        id: 'invisalign',
        title: 'Invisalign Clear Aligners',
        titleTh: 'ทันตกรรมจัดฟันใส Invisalign',
        blurb: 'The original clear-aligner system. Removable, near-invisible, and planned with 3D ClinCheck.',
        blurbTh: 'ระบบจัดฟันใสต้นตำรับ ถอดออกได้ แทบมองไม่เห็น และวางแผนด้วยซอฟต์แวร์ ClinCheck 3 มิติ',
        priceLabel: 'From ฿ 95,000',
        duration: '12 — 18 months',
      },
      {
        id: 'clearcorrect',
        title: 'ClearCorrect Aligners',
        titleTh: 'ทันตกรรมจัดฟันใส ClearCorrect',
        blurb: 'Premium aligner alternative — equally discreet, more accessible pricing.',
        blurbTh: 'จัดฟันใสทางเลือกระดับพรีเมียม สวยงามไม่ต่างกัน ในราคาที่เข้าถึงได้มากขึ้น',
        priceLabel: 'From ฿ 65,000',
        duration: '12 — 24 months',
      },
      {
        id: 'damon',
        title: 'Damon Self-Ligating Braces',
        titleTh: 'จัดฟันระบบดามอน (Self-Ligating)',
        blurb: 'Frictionless brackets that move teeth faster, with fewer adjustment visits.',
        blurbTh: 'จัดฟันระบบดามอนแบบลดแรงเสียดทาน เคลื่อนฟันได้เร็วและนัดปรับน้อยกว่า',
        priceLabel: 'From ฿ 65,000',
        duration: '18 — 24 months',
      },
      {
        id: 'metal',
        title: 'Classic Metal Braces',
        titleTh: 'จัดฟันโลหะคลาสสิก',
        blurb: 'The proven, gold-standard treatment for complex bite cases.',
        blurbTh: 'การจัดฟันแบบดั้งเดิมที่พิสูจน์แล้วว่าได้ผลกับเคสที่ซับซ้อน',
        priceLabel: 'From ฿ 45,000',
        duration: '18 — 30 months',
      },
      {
        id: 'ceramic',
        title: 'Ceramic Tooth-Coloured Braces',
        titleTh: 'จัดฟันเซรามิกสีเหมือนฟัน',
        blurb: 'Ceramic brackets blend into your smile while delivering full mechanical control.',
        blurbTh: 'แบร็กเก็ตเซรามิกสีกลมกลืนกับฟัน พร้อมประสิทธิภาพการรักษาเต็มรูปแบบ',
        priceLabel: 'From ฿ 55,000',
        duration: '18 — 30 months',
      },
    ],
  },
  {
    id: 'implants',
    icon: 'anchor',
    title: 'Dental Implants',
    titleTh: 'ทันตกรรมรากฟันเทียม',
    blurb: 'Permanent tooth restoration using Straumann & Astra implant systems.',
    blurbTh: 'ทดแทนฟันถาวรด้วยระบบรากฟันเทียม Straumann และ Astra ระดับโลก',
    long: 'Every implant case begins with 3D cone-beam CT planning. We use only Swiss Straumann and Swedish Astra Tech systems — the most extensively studied implants in the world.',
    longTh: 'ทุกเคสรากฟันเทียมเริ่มต้นด้วยการวางแผน CT 3 มิติ เราเลือกใช้เฉพาะระบบ Straumann จากสวิตเซอร์แลนด์ และ Astra Tech จากสวีเดน ซึ่งเป็นระบบที่มีงานวิจัยรองรับมากที่สุดในโลก',
    priceFrom: 55000,
    priceLabel: 'From ฿ 55,000',
    duration: '3 — 6 months',
    feature: true,
    subServices: [
      {
        id: 'single',
        title: 'Single Tooth Implant',
        titleTh: 'รากฟันเทียมซี่เดี่ยว',
        blurb: 'One missing tooth, one titanium root, one ceramic crown. The most natural replacement available.',
        blurbTh: 'ฟันหายไปหนึ่งซี่ ทดแทนด้วยรากไทเทเนียมหนึ่งราก และครอบฟันเซรามิก — ใกล้เคียงฟันธรรมชาติที่สุด',
        priceLabel: 'From ฿ 55,000',
        duration: '3 — 6 months',
      },
      {
        id: 'all-on-4',
        title: 'All-on-4 Full-Arch',
        titleTh: 'รากฟันเทียมทั้งขากรรไกร All-on-4',
        blurb: 'Replace an entire arch of missing teeth on just four strategically placed implants.',
        blurbTh: 'ทดแทนฟันทั้งขากรรไกรด้วยรากเทียมเพียง 4 ราก ตามตำแหน่งที่วางแผนอย่างแม่นยำ',
        priceLabel: 'From ฿ 480,000',
        duration: '4 — 6 months',
      },
      {
        id: 'bridge',
        title: 'Implant-Supported Bridge',
        titleTh: 'สะพานฟันบนรากฟันเทียม',
        blurb: 'Two implants, three or four crowns — perfect for restoring several adjacent teeth.',
        blurbTh: 'รากเทียม 2 ตัว ครอบฟัน 3-4 ซี่ เหมาะกับการทดแทนฟันที่หายไปหลายซี่ติดกัน',
        priceLabel: 'From ฿ 145,000',
        duration: '4 — 6 months',
      },
      {
        id: 'immediate',
        title: 'Immediate-Load Implants',
        titleTh: 'รากฟันเทียมแบบใส่ฟันทันที',
        blurb: 'Walk out with a temporary crown the same day your implant is placed.',
        blurbTh: 'ออกจากคลินิกพร้อมครอบฟันชั่วคราวในวันเดียวกับที่ฝังราก',
        priceLabel: 'From ฿ 75,000',
        duration: '1 visit + healing',
      },
    ],
  },
  {
    id: 'veneers',
    icon: 'gem',
    title: 'Veneers & Aesthetics',
    titleTh: 'วีเนียร์และทันตกรรมความงาม',
    blurb: 'Custom-designed porcelain to reshape your smile, tooth by tooth.',
    blurbTh: 'พอร์ซเลนออกแบบเฉพาะบุคคล เพื่อปรับรูปทรงรอยยิ้มทีละซี่',
    long: 'Veneer cases begin with smile-design previews — you see the final result in your own mouth before any tooth is touched.',
    longTh: 'ทุกเคสวีเนียร์เริ่มจากการออกแบบรอยยิ้มล่วงหน้า คุณจะเห็นผลลัพธ์สุดท้ายในปากของคุณก่อนการกรอฟันใดๆ',
    priceFrom: 12500,
    priceLabel: 'From ฿ 12,500 / tooth',
    duration: '2 — 3 visits',
    feature: false,
    subServices: [
      {
        id: 'porcelain',
        title: 'Porcelain Veneers',
        titleTh: 'วีเนียร์พอร์ซเลน',
        blurb: 'Hand-crafted ceramic shells, indistinguishable from natural enamel.',
        blurbTh: 'เซรามิกที่ปั้นด้วยมือทีละชิ้น แยกไม่ออกจากเคลือบฟันธรรมชาติ',
        priceLabel: '฿ 18,500 / tooth',
        duration: '2 visits',
      },
      {
        id: 'composite',
        title: 'Composite Veneers',
        titleTh: 'วีเนียร์คอมโพสิต',
        blurb: 'Same-day artistry — sculpted directly onto your teeth in a single visit.',
        blurbTh: 'งานศิลป์ในวันเดียว เคลือบและขึ้นรูปบนฟันคุณในการนัดครั้งเดียว',
        priceLabel: '฿ 12,500 / tooth',
        duration: '1 visit',
      },
      {
        id: 'lumineers',
        title: 'Lumineers (No-Prep)',
        titleTh: 'วีเนียร์ Lumineers (ไม่ต้องกรอฟัน)',
        blurb: 'Ultra-thin shells bonded over your existing teeth — fully reversible.',
        blurbTh: 'แผ่นเซรามิกบางพิเศษ ติดทับฟันเดิมโดยไม่ต้องกรอ — สามารถถอดได้',
        priceLabel: '฿ 22,000 / tooth',
        duration: '2 visits',
      },
    ],
  },
  {
    id: 'whitening',
    icon: 'sun',
    title: 'Teeth Whitening',
    titleTh: 'ฟอกสีฟัน',
    blurb: 'Clinical-grade brightening with Philips Zoom and custom take-home trays.',
    blurbTh: 'ฟอกสีฟันระดับคลินิกด้วยเทคโนโลยี Philips Zoom และชุดถาดฟอกที่ทำเฉพาะบุคคล',
    long: 'Our whitening protocols are designed to brighten without sensitivity. Every patient gets a custom-fit tray for safe maintenance at home.',
    longTh: 'โปรโตคอลการฟอกสีฟันของเราออกแบบมาเพื่อความขาวสว่างโดยไม่เกิดอาการเสียวฟัน ทุกคนได้รับถาดฟอกที่เข้าพอดีกับฟันสำหรับการดูแลต่อที่บ้าน',
    priceFrom: 4500,
    priceLabel: 'From ฿ 4,500',
    duration: '1 visit',
    feature: false,
    subServices: [
      {
        id: 'zoom',
        title: 'Philips Zoom In-Clinic',
        titleTh: 'ฟอกสีฟันที่คลินิกด้วย Philips Zoom',
        blurb: 'Brighter teeth in a single 60-minute visit, with sensitivity-minimising protocol.',
        blurbTh: 'ฟันขาวสว่างในการนัดเดียว 60 นาที พร้อมโปรโตคอลลดการเสียวฟัน',
        priceLabel: '฿ 8,500',
        duration: '60 min',
      },
      {
        id: 'cold-light',
        title: 'Cold-Light Whitening',
        titleTh: 'ฟอกสีฟันด้วยแสงเย็น',
        blurb: 'Gentle, heatless LED activation — ideal for sensitive teeth.',
        blurbTh: 'การฟอกด้วยแสง LED ไม่ร้อน เหมาะกับผู้ที่มีฟันเสียวง่าย',
        priceLabel: '฿ 6,500',
        duration: '45 min',
      },
      {
        id: 'home-kit',
        title: 'Take-Home Tray Kit',
        titleTh: 'ชุดถาดฟอกสีฟันที่บ้าน',
        blurb: 'Custom-moulded trays plus pharmaceutical-grade gel — gradual, gentle results.',
        blurbTh: 'ถาดฟอกที่ขึ้นรูปเฉพาะบุคคล พร้อมเจลคุณภาพเภสัชกรรม — ผลลัพธ์ค่อยเป็นค่อยไปอย่างนุ่มนวล',
        priceLabel: '฿ 4,500',
        duration: '14 nights',
      },
    ],
  },
  {
    id: 'general',
    icon: 'smile',
    title: 'General Dentistry',
    titleTh: 'ทันตกรรมทั่วไป',
    blurb: 'Routine examinations, cleanings, fillings, and root-canal therapy.',
    blurbTh: 'ตรวจฟัน ขูดหินปูน อุดฟัน และรักษารากฟัน อย่างละเอียดและนุ่มนวล',
    long: 'Routine care is the backbone of a healthy smile. Our hygienists use ultrasonic scalers and air-polishing for a gentle, thorough clean every six months.',
    longTh: 'การดูแลประจำคือพื้นฐานของสุขภาพช่องปากที่ดี นักทันตอนามัยของเราใช้เครื่องอัลตราโซนิกและระบบ Air Polishing เพื่อความสะอาดละเอียดอ่อนทุก 6 เดือน',
    priceFrom: 800,
    priceLabel: 'From ฿ 800',
    duration: '30 — 60 min',
    feature: false,
    subServices: [
      {
        id: 'cleaning',
        title: 'Scaling & Polishing',
        titleTh: 'ขูดหินปูนและขัดฟัน',
        blurb: 'Ultrasonic deep clean plus air-polish finish — every six months.',
        blurbTh: 'ทำความสะอาดด้วยอัลตราโซนิกและขัดด้วย Air Polishing ทุก 6 เดือน',
        priceLabel: '฿ 800',
        duration: '45 min',
      },
      {
        id: 'filling',
        title: 'Aesthetic Tooth Fillings',
        titleTh: 'อุดฟันด้วยวัสดุสีเหมือนฟัน',
        blurb: 'Tooth-coloured composite restorations bonded with modern adhesive systems.',
        blurbTh: 'อุดฟันด้วยวัสดุคอมโพสิตสีเหมือนฟัน ติดแน่นด้วยระบบกาวยุคใหม่',
        priceLabel: 'From ฿ 1,500',
        duration: '30 min',
      },
      {
        id: 'root-canal',
        title: 'Root Canal Therapy',
        titleTh: 'รักษารากฟัน',
        blurb: 'Endodontic treatment using rotary nickel-titanium systems for predictable results.',
        blurbTh: 'รักษารากฟันด้วยระบบเครื่องมือนิกเกิล-ไทเทเนียมหมุน เพื่อผลลัพธ์ที่แม่นยำ',
        priceLabel: 'From ฿ 8,500',
        duration: '60 — 90 min',
      },
      {
        id: 'extraction',
        title: 'Wisdom Tooth Extraction',
        titleTh: 'ผ่าฟันคุด',
        blurb: 'Surgical removal with conscious sedation options for nervous patients.',
        blurbTh: 'ผ่าฟันคุดอย่างปลอดภัย พร้อมทางเลือกในการให้ยาสลบเบาสำหรับผู้ที่กังวล',
        priceLabel: 'From ฿ 3,500',
        duration: '45 min',
      },
    ],
  },
  {
    id: 'pediatric',
    icon: 'baby',
    title: 'Pediatric Dentistry',
    titleTh: 'ทันตกรรมสำหรับเด็ก',
    blurb: 'Gentle, patient first dental experiences designed for children.',
    blurbTh: 'ประสบการณ์ทันตกรรมแสนอบอุ่น ออกแบบมาเพื่อหัวใจน้อยๆ ของลูกคุณโดยเฉพาะ',
    long: 'Our pediatric rooms are designed to feel calm rather than clinical, with friendly visual storytelling and child-sized equipment.',
    longTh: 'ห้องตรวจฟันสำหรับเด็กของเราออกแบบให้ดูอบอุ่น ไม่เหมือนคลินิก พร้อมการสื่อสารแบบเล่าเรื่องและอุปกรณ์ขนาดเล็กเหมาะกับเด็ก',
    priceFrom: 600,
    priceLabel: 'From ฿ 600',
    duration: '20 — 45 min',
    feature: false,
    subServices: [
      {
        id: 'first-visit',
        title: 'First Dental Visit',
        titleTh: 'ตรวจฟันครั้งแรกของลูก',
        blurb: 'A friendly, no-pressure introduction to the dentist — for children aged 2+.',
        blurbTh: 'การพบหมอฟันครั้งแรกอย่างนุ่มนวลและไม่กดดัน สำหรับลูกอายุ 2 ปีขึ้นไป',
        priceLabel: '฿ 600',
        duration: '20 min',
      },
      {
        id: 'fluoride',
        title: 'Fluoride Treatment',
        titleTh: 'เคลือบฟลูออไรด์',
        blurb: 'Strengthens developing enamel against early decay.',
        blurbTh: 'เสริมความแข็งแรงให้กับเคลือบฟันที่กำลังพัฒนา ป้องกันฟันผุระยะเริ่มต้น',
        priceLabel: '฿ 800',
        duration: '20 min',
      },
      {
        id: 'sealant',
        title: 'Pit & Fissure Sealants',
        titleTh: 'เคลือบหลุมร่องฟัน',
        blurb: 'Protective resin coatings that prevent cavities in molar grooves.',
        blurbTh: 'เคลือบเรซินป้องกัน ลดการเกิดฟันผุบนร่องฟันกรามด้านบดเคี้ยว',
        priceLabel: '฿ 1,200 / tooth',
        duration: '30 min',
      },
    ],
  },
];

// ---------- Doctors with branch schedules ----------
// Schedule format: list of {branch, day, weeks}
// weeks = [1..5] means "1st through 5th week of month" (5 = if applicable)
const DOCTORS = [
  {
    id: 'pichaya',
    name: 'Dr. Pichaya Saetang',
    nameTh: 'ทพญ. พิชญา แซ่ตั้ง',
    nameShort: 'Pichaya',
    role: 'Orthodontics',
    roleTh: 'ทันตแพทย์เฉพาะทางจัดฟัน',
    cred: 'DDS, MSc Orthodontics, Mahidol',
    years: 12,
    bio: 'Dr. Pichaya has been planning braces and aligner cases at We Smile since the clinic opened in 2014. She trained at Mahidol University and continues to advance her Invisalign clear-aligner protocols every year.',
    bioTh: 'ทพญ. พิชญา ดูแลเคสจัดฟันและจัดฟันใสที่ We Smile ตั้งแต่เปิดคลินิกในปี 2557 จบการศึกษาจากคณะทันตแพทยศาสตร์ มหาวิทยาลัยมหิดล และยังคงพัฒนาเทคนิค Invisalign อย่างต่อเนื่องทุกปี',
    photo: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=600&auto=format&fit=crop',
    specialties: ['orthodontics'],
    languages: ['Thai', 'English', 'จีนกลางพื้นฐาน'],
    certifications: [
      { year: 2012, item: 'Doctor of Dental Surgery (DDS), Mahidol University' },
      { year: 2015, item: 'MSc in Orthodontics, Mahidol University' },
      { year: 2018, item: 'Certified Invisalign Provider — Platinum Level' },
      { year: 2021, item: 'Damon System Advanced Certification' },
      { year: 2024, item: 'Member, Thai Association of Orthodontists' },
    ],
    schedule: [
      { branch: 'ladkrabang', day: 'mon', weeks: [1,2,3,4,5] },
      { branch: 'ladkrabang', day: 'wed', weeks: [1,3,5] },
      { branch: 'suvarnabhumi', day: 'tue', weeks: [2,3,4] },
      { branch: 'onnut', day: 'sat', weeks: [1,3] },
      { branch: 'onnut', day: 'sun', weeks: [3] },
    ],
  },
  {
    id: 'anusorn',
    name: 'Dr. Anusorn Klangphoo',
    nameTh: 'ทพ. อนุสรณ์ กลั่นภู่',
    nameShort: 'Anusorn',
    role: 'Implantology',
    roleTh: 'ทันตแพทย์เฉพาะทางรากฟันเทียม',
    cred: 'DDS, Implant Specialist, Chula',
    years: 14,
    bio: 'Dr. Anusorn is the implant lead at We Smile, with over 1,200 implants placed using Straumann and Astra Tech systems. He explains every step before treatment begins and personally follows every healing visit.',
    bioTh: 'ทพ. อนุสรณ์ เป็นหัวหน้าทีมรากฟันเทียมของ We Smile ใส่รากฟันเทียมมาแล้วกว่า 1,200 ราย ด้วยระบบ Straumann และ Astra Tech อธิบายทุกขั้นตอนก่อนเริ่มรักษา และติดตามผลทุกครั้งด้วยตัวเอง',
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=600&auto=format&fit=crop',
    specialties: ['implants', 'general'],
    languages: ['Thai', 'English'],
    certifications: [
      { year: 2010, item: 'Doctor of Dental Surgery (DDS), Chulalongkorn University' },
      { year: 2014, item: 'Higher Graduate Diploma in Implant Dentistry, Chula' },
      { year: 2017, item: 'Straumann Surgical Certification — Master Level' },
      { year: 2020, item: 'All-on-4 Treatment Concept Certified Provider' },
      { year: 2023, item: 'ITI (International Team for Implantology) Fellow' },
    ],
    schedule: [
      { branch: 'ladkrabang', day: 'tue', weeks: [1,2,3,4,5] },
      { branch: 'ladkrabang', day: 'thu', weeks: [1,2,3,4,5] },
      { branch: 'suvarnabhumi', day: 'mon', weeks: [2,4] },
      { branch: 'suvarnabhumi', day: 'fri', weeks: [1,3] },
      { branch: 'romklao', day: 'sat', weeks: [2,4] },
    ],
  },
  {
    id: 'suchada',
    name: 'Dr. Suchada Tantisira',
    nameTh: 'ทพญ. สุชาดา ตันติศิระ',
    nameShort: 'Suchada',
    role: 'Aesthetic Dentistry',
    roleTh: 'ทันตแพทย์ความงามและวีเนียร์',
    cred: 'DDS, Cosmetic & Veneers',
    years: 9,
    bio: 'Dr. Suchada specialises in smile design — veneers, whitening, and crown work. She approaches every case as an art commission: we sketch your ideal smile together before any tooth is touched.',
    bioTh: 'ทพญ. สุชาดา เชี่ยวชาญด้านการออกแบบรอยยิ้ม วีเนียร์ ฟอกสีฟัน และครอบฟัน เธอมองทุกเคสเหมือนงานศิลป์ — เริ่มต้นด้วยการสเก็ตช์รอยยิ้มในอุดมคติของคุณก่อนการกรอฟันใดๆ',
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&auto=format&fit=crop',
    specialties: ['veneers', 'whitening', 'general'],
    languages: ['Thai', 'English', 'Korean'],
    certifications: [
      { year: 2015, item: 'Doctor of Dental Surgery (DDS), Mahidol University' },
      { year: 2018, item: 'Advanced Aesthetic Dentistry, NYU Continuing Education' },
      { year: 2020, item: 'Digital Smile Design (DSD) Certified Master' },
      { year: 2022, item: 'Empress & e.max Porcelain Veneer Specialist' },
      { year: 2024, item: 'Member, Thai Academy of Aesthetic Dentistry' },
    ],
    schedule: [
      { branch: 'ladkrabang', day: 'fri', weeks: [1,2,3,4,5] },
      { branch: 'ladkrabang', day: 'sat', weeks: [1,3,5] },
      { branch: 'onnut', day: 'mon', weeks: [2,4] },
      { branch: 'onnut', day: 'wed', weeks: [1,3] },
      { branch: 'suvarnabhumi', day: 'sun', weeks: [2,4] },
    ],
  },
  {
    id: 'nattaya',
    name: 'Dr. Nattaya Reungpoom',
    nameTh: 'ทพญ. ณัฐญา เริงภูมิ',
    nameShort: 'Nattaya',
    role: 'General & Pediatric',
    roleTh: 'ทันตกรรมทั่วไปและเด็ก',
    cred: 'DDS, Pediatric Specialist',
    years: 7,
    bio: 'Dr. Nattaya is most patients\' first contact at We Smile — routine check-ups, cleanings, and gentle care for the youngest visitors. Families across Ladkrabang know her by name.',
    bioTh: 'ทพญ. ณัฐญา คือหมอที่ดูแลคนไข้คนใหม่ทุกราย ตรวจฟัน ขูดหินปูน และดูแลน้องๆ ด้วยความนุ่มนวล ครอบครัวในย่านลาดกระบังต่างจดจำเธอได้',
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=600&auto=format&fit=crop',
    specialties: ['general', 'pediatric'],
    languages: ['Thai', 'English'],
    certifications: [
      { year: 2017, item: 'Doctor of Dental Surgery (DDS), Khon Kaen University' },
      { year: 2019, item: 'Higher Diploma in Pediatric Dentistry, Mahidol' },
      { year: 2021, item: 'Conscious Sedation for Pediatric Patients Certified' },
      { year: 2023, item: 'Member, Thai Society of Pediatric Dentistry' },
    ],
    schedule: [
      { branch: 'ladkrabang', day: 'wed', weeks: [2,4] },
      { branch: 'ladkrabang', day: 'sun', weeks: [1,2,3,4,5] },
      { branch: 'romklao', day: 'mon', weeks: [1,2,3,4,5] },
      { branch: 'romklao', day: 'thu', weeks: [1,3,5] },
      { branch: 'romklao', day: 'fri', weeks: [2,4] },
    ],
  },
];

// ---------- FAQ ----------
const FAQS = [
  {
    q: 'Do you accept walk-in patients?',
    qTh: 'รับคนไข้ที่ไม่ได้นัดล่วงหน้าหรือไม่?',
    a: 'We do, but bookings are strongly recommended — same-day slots fill up quickly, especially in the evenings and on weekends. Please call 063-879-8448 or use our Booking page.',
    aTh: 'รับค่ะ แต่แนะนำให้นัดล่วงหน้า เนื่องจากคิวเต็มเร็ว โดยเฉพาะช่วงเย็นและสุดสัปดาห์ กรุณาโทร 063-879-8448 หรือนัดผ่านหน้าจองออนไลน์',
  },
  {
    q: 'Which insurance providers do you accept?',
    qTh: 'รับประกันสุขภาพของบริษัทใดบ้าง?',
    a: 'AIA, Bangkok Insurance, Muang Thai, Allianz Ayudhya, FWD, and most major Thai providers. Our team handles claim submission for in-network plans on your behalf.',
    aTh: 'AIA, กรุงเทพประกันภัย, เมืองไทย, อลิอันซ์ อยุธยา, FWD และบริษัทประกันชั้นนำของไทยส่วนใหญ่ ทีมงานยินดีดำเนินการเบิกประกันให้คุณ',
  },
  {
    q: 'How does the free consultation work?',
    qTh: 'ปรึกษาฟรีของคลินิกเป็นอย่างไร?',
    a: 'A 15-minute conversation with one of our doctors — no scans, no obligation. We listen to your goals, take a brief look at your smile, and outline options and pricing.',
    aTh: 'พูดคุยกับทันตแพทย์ของเรา 15 นาที โดยไม่มีการสแกนและไม่มีข้อผูกมัด เรารับฟังเป้าหมายของคุณ ตรวจดูรอยยิ้มเบื้องต้น และอธิบายทางเลือกพร้อมราคาให้คุณ',
  },
  {
    q: 'Do package prices include all follow-up visits?',
    qTh: 'ราคาแพ็กเกจรวมการนัดติดตามทั้งหมดหรือไม่?',
    a: 'For orthodontics and aligners, yes — the package price covers all monthly adjustments, retainers, and one full year of post-treatment follow-up. Veneers and implants are priced per tooth or implant site.',
    aTh: 'สำหรับการจัดฟันและจัดฟันใส แพ็กเกจครอบคลุมทุกครั้งของการนัดปรับเครื่องมือ retainer และการติดตามผลหลังเสร็จสิ้นการรักษาเป็นเวลา 1 ปีเต็ม ส่วนวีเนียร์และรากฟันเทียมคิดราคาตามจำนวนซี่หรือตำแหน่ง',
  },
  {
    q: 'Are the clinics open on weekends?',
    qTh: 'คลินิกเปิดบริการในวันเสาร์-อาทิตย์หรือไม่?',
    a: 'Yes — every We Smile branch is open seven days a week, including most public holidays. Hours vary slightly between branches; see the Branches page for details.',
    aTh: 'เปิดค่ะ ทุกสาขาของ We Smile เปิดให้บริการ 7 วันต่อสัปดาห์ รวมถึงวันหยุดราชการส่วนใหญ่ เวลาเปิด-ปิดอาจแตกต่างกันเล็กน้อยในแต่ละสาขา สามารถดูได้ในหน้าสาขา',
  },
  {
    q: 'Which branch should I visit?',
    qTh: 'ควรเลือกสาขาไหน?',
    a: 'Most patients choose by proximity. Specialty cases (orthodontics, implants) are concentrated at Ladkrabang and Suvarnabhumi. The Branches page shows which doctors visit each location.',
    aTh: 'คนไข้ส่วนใหญ่เลือกตามความสะดวกในการเดินทาง สำหรับเคสเฉพาะทาง (จัดฟัน รากฟันเทียม) แนะนำสาขาลาดกระบังและสุวรรณภูมิ ดูได้ในหน้าสาขาว่าหมอท่านใดออกตรวจที่สาขาใดบ้าง',
  },
];

// ---------- Testimonials (short quotes) ----------
const TESTIMONIALS = [
  {
    q: 'They explained every option carefully. I never felt rushed — the whole process felt premium from start to finish.',
    qTh: 'ทุกตัวเลือกถูกอธิบายอย่างละเอียด ไม่รู้สึกถูกเร่งเลย ทั้งกระบวนการดูพรีเมียมตั้งแต่ต้นจนจบ',
    a: 'Pim · Clear Aligners',
    aTh: 'พิม · จัดฟันใส',
    rating: 5,
  },
  {
    q: 'My dentist remembered me by name after a year. Small thing, but it told me everything.',
    qTh: 'หลังจากผ่านไปหนึ่งปี หมอยังจำชื่อฉันได้ เรื่องเล็กๆ แต่มันบอกอะไรหลายอย่าง',
    a: 'Nok · Veneers',
    aTh: 'นก · วีเนียร์',
    rating: 5,
  },
  {
    q: 'Easy booking, a beautiful clinic, and a real difference in my smile after six months of treatment.',
    qTh: 'นัดง่าย คลินิกสวยมาก และเห็นความเปลี่ยนแปลงในรอยยิ้มอย่างชัดเจนหลังการรักษา 6 เดือน',
    a: 'James · Orthodontics',
    aTh: 'เจมส์ · จัดฟัน',
    rating: 5,
  },
];

// ---------- Patient Success Stories (before/after) ----------
const SUCCESS_STORIES = [
  {
    id: 'p-aligners-1',
    patient: 'Patient · Age 26',
    patientTh: 'คนไข้ · อายุ 26 ปี',
    treatment: 'Clear Aligners',
    treatmentTh: 'จัดฟันใส Invisalign',
    duration: '14 months',
    durationTh: '14 เดือน',
    doctor: 'Dr. Pichaya',
    note: 'Mild crowding corrected with 24 trays. Whitening completed in final phase.',
    noteTh: 'แก้ไขฟันเก เรียงตัวด้วยถาดจัดฟัน 24 ชุด และฟอกสีฟันในขั้นตอนสุดท้าย',
    before: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=900&auto=format&fit=crop',
    after: 'https://images.unsplash.com/photo-1606811971618-4486d14f3f99?w=900&auto=format&fit=crop&sat=20&bri=10',
  },
  {
    id: 'p-veneers-1',
    patient: 'Patient · Age 34',
    patientTh: 'คนไข้ · อายุ 34 ปี',
    treatment: 'Porcelain Veneers',
    treatmentTh: 'วีเนียร์พอร์ซเลน',
    duration: '3 weeks',
    durationTh: '3 สัปดาห์',
    doctor: 'Dr. Suchada',
    note: '8 e.max veneers on upper anterior teeth. Digital Smile Design preview approved before prep.',
    noteTh: 'วีเนียร์ e.max จำนวน 8 ซี่ที่ฟันหน้าบน ออกแบบรอยยิ้มดิจิทัลให้คนไข้ดูก่อนเริ่มกรอ',
    before: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&auto=format&fit=crop',
    after: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=900&auto=format&fit=crop',
  },
  {
    id: 'p-implant-1',
    patient: 'Patient · Age 52',
    patientTh: 'คนไข้ · อายุ 52 ปี',
    treatment: 'Single Implant + Crown',
    treatmentTh: 'รากฟันเทียมซี่เดี่ยวพร้อมครอบฟัน',
    duration: '4 months',
    durationTh: '4 เดือน',
    doctor: 'Dr. Anusorn',
    note: 'Straumann BLT implant placed with guided surgery. Ceramic crown delivered 4 months later.',
    noteTh: 'ฝังรากเทียม Straumann BLT ด้วยระบบ Guided Surgery ใส่ครอบฟันเซรามิกหลังจากนั้น 4 เดือน',
    before: 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=900&auto=format&fit=crop',
    after: 'https://images.unsplash.com/photo-1571772996211-2f02c9727629?w=900&auto=format&fit=crop',
  },
  {
    id: 'p-whitening-1',
    patient: 'Patient · Age 29',
    patientTh: 'คนไข้ · อายุ 29 ปี',
    treatment: 'Zoom Whitening + Home Trays',
    treatmentTh: 'ฟอกสีฟัน Zoom และชุดถาดที่บ้าน',
    duration: '2 weeks',
    durationTh: '2 สัปดาห์',
    doctor: 'Dr. Suchada',
    note: 'One in-clinic Zoom session followed by 10 nights of custom-tray maintenance. Five shades brighter.',
    noteTh: 'ฟอกสีฟัน Zoom 1 ครั้งที่คลินิก ตามด้วยการใช้ถาดฟอกที่บ้าน 10 คืน ฟันขาวขึ้น 5 ระดับ',
    before: 'https://images.unsplash.com/photo-1612538498488-3fadd07e7b54?w=900&auto=format&fit=crop',
    after: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=900&auto=format&fit=crop',
  },
  {
    id: 'p-ortho-1',
    patient: 'Patient · Age 19',
    patientTh: 'คนไข้ · อายุ 19 ปี',
    treatment: 'Damon Self-Ligating Braces',
    treatmentTh: 'จัดฟันระบบดามอน',
    duration: '22 months',
    durationTh: '22 เดือน',
    doctor: 'Dr. Pichaya',
    note: 'Significant crowding and crossbite resolved without extraction.',
    noteTh: 'แก้ไขปัญหาฟันซ้อนเกและฟันสบไขว้ได้สำเร็จโดยไม่ต้องถอนฟัน',
    before: 'https://images.unsplash.com/photo-1559591935-c6c92c6e1c7b?w=900&auto=format&fit=crop',
    after: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=900&auto=format&fit=crop',
  },
];

// ---------- "What We Do" — editable hero copy (CMS-driven) ----------
const WHAT_WE_DO = {
  eyebrow: 'What we do',
  eyebrowTh: 'บริการของเรา',
  title: 'Comprehensive care, under one roof.',
  titleTh: 'การดูแลทุกขั้นตอน ภายใต้หลังคาเดียว',
  lead: 'Six core specialties — every stage of your dental journey, with specialists who explain things in plain words.',
  leadTh: 'หกสาขาความเชี่ยวชาญหลัก ครอบคลุมทุกขั้นตอนของการดูแลรอยยิ้มคุณ โดยทันตแพทย์เฉพาะทางที่อธิบายเข้าใจง่าย',
  // Each card can override title/blurb/image if the CMS user wants
  // (kept null = use service defaults from SERVICES array)
  overrides: {
    // 'orthodontics': { image: '...', title: '...' },
  },
};

// ---------- Helpers ----------
function getService(id) { return SERVICES.find(s => s.id === id); }
function getDoctor(id) { return DOCTORS.find(d => d.id === id); }
function getBranch(id) { return BRANCHES.find(b => b.id === id); }
function getSubService(catId, subId) {
  const cat = getService(catId);
  return cat?.subServices?.find(s => s.id === subId);
}
function getStoriesForSubService(subId) {
  // Use service id matching or hand-curated mapping; for now return all
  return SUCCESS_STORIES;
}
function getDoctorsForSpecialty(serviceId) {
  return DOCTORS.filter(d => d.specialties?.includes(serviceId));
}

Object.assign(window, {
  BRANCHES, SERVICES, DOCTORS, FAQS, TESTIMONIALS, SUCCESS_STORIES, WHAT_WE_DO,
  getService, getDoctor, getBranch, getSubService,
  getStoriesForSubService, getDoctorsForSpecialty,
});
